
language: go

go:
  - "1.10"

script:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go test -v -cover ./... -coverprofile=coverage.out
  - gover
  - goveralls -service=travis-ci -coverprofile=coverage.out -repotoken=4fMYoZk0VmlhjD1RVNStLpprUXJckdCd6